# If launch in i3/config the scratchpads are not spawn (race condition?)
urxvtd -o -q -f

# merge .Xressources file
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Run ssh-agent
# trap 'test -n "$SSH_AUTH_SOCK" && eval `/usr/bin/ssh-agent -k`' 0

# maps caps lock to escape for vim 
# e setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &
xkbcomp $HOME/.dotfiles/xorg-server/xkb.config $DISPLAY
xcape -t 500 -e "ISO_Level3_Shift=Escape"
# personnalized keyboard keys for sound
xmodmap ~/.Xmodmap

exec i3
