#!/usr/bin/env bash

 xrandr --dpi 117
# If launch in i3/config the scratchpads are not spawn (race condition?)
urxvtd -o -q -f

# merge .Xressources file
[[ -f $XDG_CONFIG_HOME/X11/xresources ]] && xrdb -merge $XDG_CONFIG_HOME/X11/xresources

# maps caps lock to the escape key AND left control key (for Neovim and because it's so sweet).
xkbcomp $HOME/.dotfiles/xorg-server/xkb.config $DISPLAY && xcape -t 500 -e "ISO_Level3_Shift=Escape"

# personnalized keyboard keys
[[ -f $XDG_CONFIG_HOME/X11/xmodmap ]] && xmodmap $XDG_CONFIG_HOME/X11/xmodmap

xkbcomp $HOME/.dotfiles/xorg-server/xkb.config $DISPLAY
xcape -t 500 -e "ISO_Level3_Shift=Escape"

# mpd
[ ! -s ~/.config/mpd/pid ] && mpd

# Increase key rate
# xset r rate 300 30

# Set back to the default
#xset r rate

udiskie &

exec i3
