xrandr --dpi 144
# If launch in i3/config the scratchpads are not spawn (race condition?)
urxvtd -o -q -f

# merge .Xressources file
[[ -f $XDG_CONFIG_HOME/X11/xresources ]] && xrdb -merge $XDG_CONFIG_HOME/X11/xresources

# maps caps lock to escape for vim 
xkbcomp $HOME/.dotfiles/xorg-server/xkb.config $DISPLAY && xcape -t 500 -e "ISO_Level3_Shift=Escape"

# personnalized keyboard keys
[[ -f $XDG_CONFIG_HOME/X11/xmodmap ]] && xmodmap $XDG_CONFIG_HOME/X11/xmodmap

xkbcomp $HOME/.dotfiles/xorg-server/xkb.config $DISPLAY
xcape -t 500 -e "ISO_Level3_Shift=Escape"

# mpd
[ ! -s ~/.config/mpd/pid ] && mpd

udiskie &

exec i3
